import { readFile } from "node:fs/promises";
import { basename, extname, join } from "node:path";

/**
 * Serves a source walkthrough back to /dev/import, so a world generated by the
 * script can still be given the sound it was filmed with.
 *
 * The audio in this app is never reconstructed — it is lifted off the video in
 * the browser at capture time. A world imported from its id alone has no video
 * to lift from and therefore no sound, which is the one thing that would make
 * an imported capture worse than a captured one. Handing the file back closes
 * that gap without changing how audio works anywhere else.
 *
 * Only names that appear in the manifest are served, and only their basename.
 * Anything else is a request to read an arbitrary file off the machine through
 * a route that exists for a development convenience.
 */
export async function GET(req: Request) {
  const asked = new URL(req.url).searchParams.get("name");
  if (!asked) {
    return Response.json({ error: "name is required" }, { status: 400 });
  }

  // basename first, so "../../.env.local" can only ever ask for ".env.local",
  // which the manifest check below then refuses.
  const name = basename(asked);

  try {
    const manifest = JSON.parse(
      await readFile(join(process.cwd(), "scripts", "worldlabs-runs.json"), "utf8"),
    ) as { runs?: { source_video?: string }[] };

    const known = new Set(
      (manifest.runs ?? [])
        .map((run) => run.source_video)
        .filter((video): video is string => Boolean(video))
        .map((video) => basename(video)),
    );
    if (!known.has(name)) {
      return Response.json(
        { error: `${name} is not a source video in the manifest` },
        { status: 404 },
      );
    }

    const bytes = await readFile(join(process.cwd(), name));
    return new Response(bytes as unknown as BodyInit, {
      headers: {
        "Content-Type":
          extname(name).toLowerCase() === ".mov" ? "video/quicktime" : "video/mp4",
        "Content-Length": String(bytes.length),
      },
    });
  } catch {
    // The manifest names it, but it is not beside the checkout any more — the
    // videos are gitignored, so this is the normal state on anyone else's clone.
    return Response.json(
      { error: `${name} is not in the project directory` },
      { status: 404 },
    );
  }
}
