import { readFile } from "node:fs/promises";
import { join } from "node:path";

/**
 * The manifest of worlds generated by scripts/worldlabs.mjs, for /dev/import.
 *
 * It sits on disk beside the script rather than in public/, so the browser
 * cannot read it directly — and it should not be in public/, since it is a
 * development record rather than something every visitor should download.
 *
 * Reading it needs the filesystem, which means this is a route handler and not
 * a fetch from the page. Nothing here is secret: world ids, models, and what
 * each generation cost.
 */
export async function GET() {
  try {
    const path = join(process.cwd(), "scripts", "worldlabs-runs.json");
    const body = JSON.parse(await readFile(path, "utf8")) as {
      runs?: unknown[];
    };
    return Response.json({ runs: body.runs ?? [] });
  } catch (error) {
    const missing =
      error instanceof Error && "code" in error && error.code === "ENOENT";
    return Response.json(
      {
        error: missing
          ? "No scripts/worldlabs-runs.json — nothing has been generated yet."
          : "Could not read scripts/worldlabs-runs.json",
      },
      { status: missing ? 404 : 500 },
    );
  }
}
